### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gab1992** [rjruizfdez/insta-unfollow#28]
## Expected vs Actual Behavior
Super unfollow doesn't work "there was an error..."

## Specifications

 - Operative system: Kali Linux 

 - Version (e.g. Python version): 3.8.6

## Steps to Reproduce the Problem

When I launch the program, this time I get the `Note: There was an error unfollowing nameofuser, please try again later.` each time.
I thought yesterday it was Instagram limit but when I do it manually it works. It's not the Instagram limit.

Could it be private account ?

**Comment by ricardojoserf** [comment]
Hi @gab1992! Could you try from a different IP address using a VPN for example? To check if maybe what got flagged is your IP 
Also please try the master branch, yesterday I merged it!
I will try this later this afternoon and see if I get this error too

**Comment by gab1992** [comment]
Okay I will try with a different IP.
I am working with the last code already ;)
I will keep you inform

**Comment by ricardojoserf** [comment]
Hi @gab1992 ! I am testing the script and it is working without problem to me. Could you try with another account or from other IP address?

**Comment by gab1992** [comment]
IP changed, working !

**Comment by ricardojoserf** [comment]
Great :)
