### ISSUE TITLE
Follow from location AND tag

### ISSUE THREAD

**Issue by Jungleandmusic** [rjruizfdez/insta-unfollow#29]
First of all thanks a lot for the great job done here. Is there any way to follow someone with location and tag.
example : following guitarplayers from norway
thank you

**Comment by ricardojoserf** [comment]
Hi @Jungleandmusic ! Thank you for your kind words. I am afraid it is not possible to do this since the API does not offer this options. If I get to discover how to do this in the future I will let you know in this thread :)

**Comment by ricardojoserf** [comment]
I will let you know if I find out something related to this in the future or the API functionality changes to allow this!

Regards
