### ISSUE TITLE
AttributeError: 'InstagramAPI' object has no attribute 'username_id'

### ISSUE THREAD

**Issue by rmdhfz** [rjruizfdez/insta-unfollow#30]
## Expected vs Actual Behavior
Expected: username_id (maybe)
Actual Behavior: AttributeError: 'InstagramAPI' object has no attribute 'username_id'

## Specifications

 - Operative system: WIN 10

 - Version (e.g. Python version):  3.9.0

**Comment by ricardojoserf** [comment]
Hi @rmdhfz , that may be because you used the script too much. Did it happen when you started using it or after some time?

**Comment by ricardojoserf** [comment]
Hi @rmdhfz if you could tell me more about this I will reopen the issue, I will close it by now

**Comment by lakshaycodes** [comment]
It happened with me the first time I used the script.

**Comment by rmdhfz** [comment]
Yes @lakshaycodes , Have you found the solution?

**Comment by lakshaycodes** [comment]
no! but I left the Project...
