### ISSUE TITLE
i have this problem

### ISSUE THREAD

**Issue by b00walk3r** [rjruizfdez/insta-unfollow#33]
Note: There was an error unfollowing ********
![Ekran görüntüsü 2021-03-sdsds21 174027](https://user-images.githubusercontent.com/75166272/111909030-a4263300-8a6c-11eb-98e1-01183a88632c.png)
, please try again later

**Comment by ricardojoserf** [comment]
Hi @b00walk3r , that is because the account has reached the Instagram limit and it can not keep unfollowing other accounts. Does this happen if you try again some time later?

**Comment by b00walk3r** [comment]
okay thanks. i will look

**Comment by ricardojoserf** [comment]
Great! Let me know if waiting fixes the problem. Also it could be your IP address has been flagged, you could try using a VPN if the problem persists when using other account

**Comment by b00walk3r** [comment]
thank you i will try when i go home

**Comment by b00walk3r** [comment]
the problem has been solved thanks a lot
