### ISSUE TITLE
Sorry, but 

### ISSUE THREAD

**Issue by Leliksey** [rjruizfdez/insta-unfollow#34]
## Expected vs Actual Behavior
Sorry, i'm a new gay in python, how can i run this command? In terminal or some one else?

## Specifications

 - Operative system:

 - Version (e.g. Python version):

**Comment by ricardojoserf** [comment]
Hi @Leliksey . Yes you must run it from terminal, there are examples in the README file

**Comment by Leliksey** [comment]
Thank you

Вс, 21 марта 2021 г. в 23:21, Ricardo Ruiz ***@***.***>:

**Comment by ricardojoserf** [comment]
You are welcome!
