### ISSUE TITLE
Follow from list error

### ISSUE THREAD

**Issue by fagand** [rjruizfdez/insta-unfollow#35]
## Expected vs Actual Behavior
I have a [list.txt](https://github.com/ricardojoserf/instagram-followers-bot/files/6210125/list.txt) file that I have scraped from @instagram's followers. When I try to run the command to follow the list, I get the error: 

`Note: There was an error unfollowing btwmuskan, please try again later.
Following btwmuskan (with id 0)`
<img width="697" alt="Screenshot 2021-03-26 at 7 46 05 am" src="https://user-images.githubusercontent.com/47316903/112599131-68da8a00-8e07-11eb-9586-fd753eed6bf1.png">

Since getting this error, I have tried running the command of following users by tag and that works, so I'm confident I haven't reached my follow limit or had my IP blocked.

## Specifications

 - Operative system:

 - Version (e.g. Python version):
3

## Steps to Reproduce the Problem
-u USERNAME -p PASSWORD -o follow-list -t list.txt

**Comment by ricardojoserf** [comment]
Hi @fagand . I am not sure this is a bug, in my case it works fine so the functionality of retrieving the id still works. Maybe you reached the unfollow limit. Did you test this again? If yes and the error persists, please let me know

**Comment by ricardojoserf** [comment]
I add the image of the users followed. The problem is that some of them do not exist

![image](https://user-images.githubusercontent.com/11477353/113616213-1a25bf00-9655-11eb-842a-7db92409ddae.png)

**Comment by fagand** [comment]
Thanks for getting back to me, I pulled the code again and it worked this time. I'm not sure what was the issue previously. I'll close the issue, thanks again.

**Comment by ricardojoserf** [comment]
Great to hear! And you are welcome ;)
