### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by R3test678** [rjruizfdez/insta-unfollow#38]
## Expected vs Actual Behavior
Python3, receiving error: Eote: There was an error unfollowing XXX, please try again later.

Happens to all unfollowers, not unfollowed one yet.

## Specifications

 - Operative system:
ubuntu 18.04
 - Version (e.g. Python version):
python3 3.8.5

## Steps to Reproduce the Problem
just run the script with super unfollow

**Comment by ricardojoserf** [comment]
Hi @R3test678 
Could this be because you had already done a lot of requests to instagram with that account? Could you tell me if this happens today too?
Regards

**Comment by ricardojoserf** [comment]
Closing as I am not receiving any answer
