### ISSUE TITLE
Error :There was an error unfollowing 

### ISSUE THREAD

**Issue by popk911** [rjruizfdez/insta-unfollow#39]
## Expected vs Actual Behavior
 follow from list : 

Note: There was an error unfollowing xxxx please try again later.
Following xxxx (with id 0)

Note: There was an error unfollowing xxxx please try again later.
Following xxxx (with id 0)

but not following

## Specifications

 - Operative system: ubuntu 

 - Version (e.g. Python version): 3.9.4

**Comment by popk911** [comment]
super unfollow : 

python3 main.py -u username-p password-o super-unfollow

Output :

1) Unfollowing max10social

Note: There was an error unfollowing max10social, please try again later.
2) Unfollowing carnoisser

Note: There was an error unfollowing carnoisser, please try again later.
3) Unfollowing realchrisfischer

Note: There was an error unfollowing realchrisfischer, please try again later.
4) Unfollowing sudeepks23

Note: There was an error unfollowing sudeepks23, please try again later.

not unfollowing

**Comment by rjworks** [comment]
Did you fix it?

**Comment by ricardojoserf** [comment]
Hi @rjworks @popk911 ! This is an error related to the maximum requests to Instagram I think, but I will review it as soon as I can

**Comment by ricardojoserf** [comment]
Hi is it still happenning @rjworks @popk911 ?

**Comment by ricardojoserf** [comment]
I cant reproduce this, it is probably a problem with the rate limit in instagram
