### ISSUE TITLE
The information about my followers it's not accurate 

### ISSUE THREAD

**Issue by danilosoarescardoso** [rjruizfdez/insta-unfollow#40]
## Expected vs Actual Behavior
When I'm running the command above to list my followers info, the list of users who does not follow me back it's not quite right. It's showing even my wife doesn't following me haha

> python main.py -u USERNAME -p PASSWORD -o info

## Specifications

 - Operative system: Windows 

 - Version (e.g. Python version): 3.9.2

**Comment by ricardojoserf** [comment]
Hi @danilosoarescardoso 

I just tested this today and it seems to work fine for me. Could you let me know if this is still happenning to you?

Regards,

Ricardo

**Comment by ricardojoserf** [comment]
Hi!

I tested again and still working, and I am not getting feedback. I will close it by now :)

Regards,

Ricardo
