### ISSUE TITLE
Error username_id

### ISSUE THREAD

**Issue by josepfm** [rjruizfdez/insta-unfollow#42]
I have this error: 

AttributeError: 'InstagramAPI' object has no attribute 'username_id'

Any help?

**Comment by ricardojoserf** [comment]
Hi @josepfm , that probably means that the authentication failed

**Comment by josepfm** [comment]
Hello Ricardo,

Have you been able to test it?

I have tried it again with other accounts and I still get an error.

Could you help me?

Thanks!

**Comment by ricardojoserf** [comment]
Hi @josepfm . Could it be that the account is blocked? or maybe you are using "$" sign in the password and generates errors. Maybe you can try adding the password in an environmental variable and try with that

**Comment by josepfm** [comment]
You were right.

It works perfectly, thank you!
