### ISSUE TITLE
Login not successful

### ISSUE THREAD

**Issue by melocule** [rjruizfdez/insta-unfollow#44]
Hi! 

I tried running super unfollow, but the following error occurred: 
`Login not successful
Traceback (most recent call last):
  File "C:\...\main.py", line 187, in <module>
    main()
  File "C:\...\main.py", line 143, in main
    for i in api.getTotalSelfFollowers():
  File "C:\...\InstagramAPI.py", line 162, in getTotalSelfFollowers
    return self.getTotalFollowers(self.username_id)
AttributeError: 'InstagramAPI' object has no attribute 'username_id'`

I heard that LevPasha's Instagram-API-python and other API's were deprecated last year. Is that the cause of the error?

**Comment by ricardojoserf** [comment]
Hi @melocule , in my case I do not have problem with the login. Have you tried the "info" functionality? I think maybe the problem is with the superunfollow functionality

**Comment by ricardojoserf** [comment]
Closed due to lack of response
