### ISSUE TITLE
Bug in unfollow

### ISSUE THREAD

**Issue by mahdish45** [rjruizfdez/insta-unfollow#45]
Hi 
when im using unfollow command i have problem
my error is :
There was an error unfollowing christophe_penloup_icd, please try again later.

**Comment by ricardojoserf** [comment]
Hi @mahdish45 . Was this the first account you were trying to unfollow? Had you been doing more actions with the account, such as following people? If that is the case, it is not a problem of the tool, the tool is saying there was an error and maybe it is that you did many actions in Instagram in a short period of time
