### ISSUE TITLE
bot stops working after 83 -84 follows

### ISSUE THREAD

**Issue by MasterOregano** [rjruizfdez/insta-unfollow#48]
Hello, first of all, thank you very much for creating this tool, it really helps!
So I want to run the bot for a whole day with big delays between every follow so I won't get banned, but every time I run it, the bot stops after 83 or 84 follows and exits the script.
I tried setting the maximum amount to 600 but it still exits, I even canceled the break function but it still exits.

## Specifications

 - Operative system: win 10, 64bit

 - Version: python 3.9.7 64bit

**Comment by ricardojoserf** [comment]
Try changing the value of the parameter MAXIMO to a higher number and let me know, the only other reason is that your computer runs out of resources but it should not

**Comment by MasterOregano** [comment]
I increased the Maximo to 10000 but it still stops at the 80s

**Comment by MasterOregano** [comment]
do you have a fix idea?

**Comment by ricardojoserf** [comment]
I am unable to replicate the error, probably it is related to your host machine. I would try this in a Linux environment

**Comment by MasterOregano** [comment]
I am really out of ideas, I have been trying to fix it but I am unable, I ran it on kali Ubuntu, Kali Linux, both of them on a different computer.

**Comment by ricardojoserf** [comment]
Hi @MasterOregano . Probably Instagram does not allow you to do more follow/unfollow requests because you reach a maximum they have set (and they change preiodically to avoid bots).

**Comment by MasterOregano** [comment]
ok thank you, do you have a line of code that could make the script rerun every hour?

**Comment by ricardojoserf** [comment]
Hi @MasterOregano , please check [cron](https://en.wikipedia.org/wiki/Cron) if you want to use Linux to do that, or [scheduled tasks](https://www.windowscentral.com/how-create-automated-task-using-task-scheduler-windows-10) if you want to use Windows ;)

**Comment by MasterOregano** [comment]
Thank you so much!!!
