### ISSUE TITLE
Bug in unfollows.

### ISSUE THREAD

**Issue by MasterOregano** [rjruizfdez/insta-unfollow#49]
## Expected vs Actual Behavior
There is a problem with the super unfollow command, when I try to run it I get an error "Note: There was an error unfollowing andru.terrance, please try again later." 
I have noticed that other users also had this problem but couldn't find a fix, I tried it with an account that I haven't used in months but I still get the error, any fixes?

## Specifications

 - Operative system:
windows 10
 - Version (e.g. Python version):
python 3.9.7

## Steps to Reproduce the Problem

run the "python main.py -u USERNAME -p PASSWORD -o super-unfollow" command

**Comment by ricardojoserf** [comment]
Hi, this is related with the Instagram rate limits, that message is expected

**Comment by avanzsistemas** [comment]
i'm having the same error, first i could start to unfollow users but once i unfollowed 10 users i couldn't unfollow anyone else, even tough waiting a lot of times.
